apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: shop
spec:
  containers:
    - name: toolbox
      image: nicolaka/netshoot:latest
      command: ["sleep", "36000"]
  restartPolicy: Never