apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: shop
type: Opaque
stringData:
  password: "ca1password"

  #Secret data must be base64 encoded, but stringData allows us to provide unencoded values
  #and Kubernetes will handle the encoding for us. This is more convenient for human readability 